import type { ServiceData } from '@/types'

export const services: ServiceData[] = [
  {
    slug: 'business-setup',
    title: 'Business Setup & Company Formation',
    tagline: 'Launch Your UAE Business in Days, Not Months',
    description: 'From selecting the right jurisdiction to securing your trade license, Star One manages every step of your business setup in the UAE — so you can focus on what matters.',
    icon: '🏢',
    heroStat: '3–5 Days',
    heroStatLabel: 'Average setup time',
    features: [
      { title: 'Mainland Setup', description: 'Full access to UAE market with the ability to trade anywhere in the country. Ideal for businesses targeting local clients.' },
      { title: 'Free Zone Setup', description: '100% foreign ownership, 0% import/export duties, and dedicated business ecosystems tailored to your industry.' },
      { title: 'Offshore Company', description: 'Asset protection, international holding, and confidentiality — perfect for international businesses and investors.' },
      { title: 'Activity Code Selection', description: 'Expert guidance on selecting the correct business activity codes to avoid future licensing issues or restrictions.' },
      { title: 'Government Approvals', description: 'We handle all DED, Ministry, and Free Zone authority submissions on your behalf — no queues, no confusion.' },
      { title: 'Trade Name Registration', description: 'Reserve your preferred trade name and ensure it complies with UAE naming regulations.' },
    ],
    benefits: [
      '0% personal income tax in the UAE',
      '100% foreign ownership available',
      'Strategic location — access to 2 billion+ consumers',
      'World-class infrastructure and banking',
      'Simple, fast company registration process',
      'Access to a thriving startup and investment ecosystem',
    ],
    process: [
      { step: '01', title: 'Free Consultation', description: 'We assess your business goals and recommend the optimal structure, jurisdiction, and activity codes.' },
      { step: '02', title: 'Document Preparation', description: 'We prepare and verify all required documents — passport copies, business plan, MoA, and application forms.' },
      { step: '03', title: 'License Application', description: 'We submit your application to the relevant authority and manage all correspondence with government offices.' },
      { step: '04', title: 'License Issuance', description: 'Your trade license is issued — typically within 3–5 business days. We courier the original to you.' },
    ],
    faq: [
      { q: 'How long does company setup take?', a: 'A standard free zone setup takes 3–5 business days. Mainland setups may take 5–10 days depending on the activity type and approvals required.' },
      { q: 'Can I own 100% of my company?', a: 'Yes — free zone companies allow 100% foreign ownership. Since 2021, most mainland business activities also allow 100% foreign ownership under the new FDI law.' },
      { q: 'What is the minimum capital requirement?', a: 'Most free zones have no minimum capital requirement. Some mainland activities may require share capital as per DED regulations.' },
      { q: 'Do I need a physical office?', a: 'Free zones offer flexi-desk and virtual office options. Mainland companies require a physical tenancy contract (Ejari).' },
    ],
    cta: 'Start Your Business Setup Today',
  },
  {
    slug: 'visa-immigration',
    title: 'Visa & Immigration Services',
    tagline: 'UAE Residency — For You, Your Team & Your Family',
    description: 'From employment visas to the coveted Golden Visa, Star One handles every aspect of UAE immigration — quickly, accurately, and without the stress.',
    icon: '🛂',
    heroStat: '10 Years',
    heroStatLabel: 'Golden Visa validity',
    features: [
      { title: 'Employment Visa', description: 'Full employment visa processing for your team — from initial entry permit to Emirates ID and labour card.' },
      { title: 'Golden Visa', description: 'Secure 10-year UAE residency for investors, entrepreneurs, professionals, and talented individuals.' },
      { title: 'Family Sponsorship Visa', description: 'Sponsor your spouse, children, and domestic staff for UAE residency under your visa.' },
      { title: 'Investor Visa', description: 'Long-term residency linked to your business investment or real estate holdings in the UAE.' },
      { title: 'Emirates ID (EID)', description: 'Biometric registration and Emirates ID processing — mandatory for all UAE residents.' },
      { title: 'Visa Renewals & Cancellations', description: 'Timely renewal of existing visas and proper visa cancellation when employees or dependents leave the UAE.' },
    ],
    benefits: [
      'No employer sponsorship needed with Golden Visa',
      'Sponsor unlimited family members',
      'Access to UAE healthcare and education system',
      'Multiple entry and exit privileges',
      'Drive, bank, and sign contracts as a UAE resident',
      'Pathway to long-term UAE settlement',
    ],
    process: [
      { step: '01', title: 'Eligibility Assessment', description: 'We review your situation and identify the right visa category — employment, investor, golden, or family.' },
      { step: '02', title: 'Document Collection', description: 'We provide a tailored checklist and review all documents for accuracy before submission.' },
      { step: '03', title: 'Entry Permit & Medical', description: 'We process the initial entry permit and guide you through the medical fitness test and fingerprinting.' },
      { step: '04', title: 'Emirates ID & Residency Stamp', description: 'Final residency visa stamped in passport and Emirates ID delivered — typically within 2–4 weeks.' },
    ],
    faq: [
      { q: 'Who qualifies for the UAE Golden Visa?', a: 'Investors (AED 2M+ in property or business), entrepreneurs (approved startup), professionals (salary AED 30k+/month), and outstanding students (GPA 3.75+).' },
      { q: 'How long does an employment visa take?', a: 'Standard processing takes 2–4 weeks from the date of entry permit issuance, subject to medical clearance.' },
      { q: 'Can my family live with me in UAE?', a: 'Yes. As a UAE visa holder you can sponsor your spouse, children under 18 (or 25 if studying), and domestic helpers.' },
      { q: 'What happens if I change jobs?', a: 'Under the new UAE labour law, you can transfer your visa to a new employer with proper notice and cancellation procedures.' },
    ],
    cta: 'Start Your Visa Application',
  },
  {
    slug: 'compliance',
    title: 'Compliance Services',
    tagline: 'Stay Compliant. Stay Protected.',
    description: 'The UAE regulatory landscape is evolving fast. Star One keeps your business ahead of every requirement — from UBO filings to AML policies and Economic Substance Regulations.',
    icon: '🛡️',
    heroStat: '100%',
    heroStatLabel: 'Compliance record',
    features: [
      { title: 'UBO Registration', description: 'Ultimate Beneficial Owner (UBO) registration as required by UAE Cabinet Resolution No. 58 of 2020.' },
      { title: 'KYC Documentation', description: 'Know Your Customer documentation preparation and ongoing due diligence support for regulated industries.' },
      { title: 'ESR Filing', description: 'Economic Substance Regulations (ESR) notification and report filing to avoid significant penalties.' },
      { title: 'AML Compliance', description: 'Anti-Money Laundering policy drafting, risk assessment, and compliance framework implementation.' },
      { title: 'Audit Support', description: 'Preparation for external audits — financial statement compilation, documentation review, and auditor liaison.' },
      { title: 'Regulatory Updates', description: 'Ongoing monitoring and alerts on UAE regulatory changes that affect your business.' },
    ],
    benefits: [
      'Avoid fines of up to AED 100,000 for ESR non-compliance',
      'Protect your license and business reputation',
      'Bank account maintenance and smooth renewals',
      'Expert guidance from qualified compliance specialists',
      'Ongoing support, not just a one-time filing',
      'Peace of mind — we handle the complexities',
    ],
    process: [
      { step: '01', title: 'Compliance Audit', description: 'We assess your current compliance status against all applicable UAE regulations.' },
      { step: '02', title: 'Gap Analysis', description: 'We identify gaps and prioritise required filings, registrations, and documentation.' },
      { step: '03', title: 'Implementation', description: 'We prepare, file, and submit all required compliance documents on your behalf.' },
      { step: '04', title: 'Ongoing Monitoring', description: 'We track regulatory changes and proactively alert you to upcoming requirements.' },
    ],
    faq: [
      { q: 'What is the UBO register and who must file?', a: 'All UAE mainland and free zone companies (except listed entities and government bodies) must maintain a register of their ultimate beneficial owners and file with the relevant authority.' },
      { q: 'What are ESR penalties?', a: 'Non-filing can attract penalties of AED 20,000 for first offence and AED 50,000 for subsequent violations. Serious breaches can result in license suspension.' },
      { q: 'Is AML compliance mandatory for all UAE businesses?', a: 'Designated non-financial businesses and professions (DNFBPs) including real estate agents, auditors, and company service providers are subject to AML regulations.' },
      { q: 'How often do I need to renew compliance filings?', a: 'UBO registers must be updated within 15 days of any change. ESR reports are annual. KYC documents require periodic refresh typically every 1–2 years.' },
    ],
    cta: 'Get Your Compliance Health Check',
  },
  {
    slug: 'vat-corporate-tax',
    title: 'VAT & Corporate Tax',
    tagline: 'Expert Tax Advisory for UAE Businesses',
    description: 'With VAT at 5% and Corporate Tax now at 9%, getting your tax obligations right is critical. Star One provides end-to-end tax registration, filing, and planning for businesses of all sizes.',
    icon: '📊',
    heroStat: '9%',
    heroStatLabel: 'UAE Corporate Tax rate',
    features: [
      { title: 'VAT Registration', description: 'Mandatory VAT registration for businesses exceeding AED 375,000 in annual revenue, and voluntary registration for those above AED 187,500.' },
      { title: 'VAT Return Filing', description: 'Accurate quarterly VAT returns filed on time with the Federal Tax Authority (FTA) — avoiding late filing penalties.' },
      { title: 'Corporate Tax Registration', description: 'All UAE businesses must register for Corporate Tax. We handle the FTA portal registration and setup.' },
      { title: 'Corporate Tax Filing', description: 'Annual Corporate Tax return preparation and filing within the statutory deadline.' },
      { title: 'Tax Planning & Advisory', description: 'Strategic advice on tax-efficient structures, qualifying free zone status, and deduction optimisation.' },
      { title: 'FTA Audit Support', description: 'Representation and documentation support during Federal Tax Authority investigations and audits.' },
    ],
    benefits: [
      'No penalties for late or incorrect filings',
      'Optimise deductions and minimise tax liability legally',
      'Understand qualifying free zone entity status',
      'Expert interpretation of UAE tax law',
      'Timely filing — we track every deadline',
      'Ongoing advisory as laws evolve',
    ],
    process: [
      { step: '01', title: 'Tax Assessment', description: 'We review your business structure, revenue, and activities to determine your full tax obligations.' },
      { step: '02', title: 'Registration', description: 'We complete all FTA registrations — VAT, Corporate Tax, and Excise (where applicable).' },
      { step: '03', title: 'Bookkeeping & Records', description: 'We ensure your accounting records meet the standards required for accurate tax calculation and FTA compliance.' },
      { step: '04', title: 'Filing & Payment', description: 'We prepare and file your returns on time, every time — and advise on tax payment scheduling.' },
    ],
    faq: [
      { q: 'When did UAE Corporate Tax come into effect?', a: 'Corporate Tax applies to financial years beginning on or after 1 June 2023, at a rate of 9% on taxable income exceeding AED 375,000.' },
      { q: 'Are free zone companies exempt from Corporate Tax?', a: 'Qualifying Free Zone Persons (QFZPs) can benefit from a 0% Corporate Tax rate on qualifying income, subject to meeting specific substance and income conditions.' },
      { q: 'What is the VAT rate in the UAE?', a: 'The standard VAT rate is 5%. Some goods and services are zero-rated (0%) or exempt, such as healthcare, education, and certain financial services.' },
      { q: 'What are the penalties for late VAT filing?', a: 'Late registration: AED 20,000. Late filing: AED 1,000 for first offence, AED 2,000 for subsequent. Late payment: 2–300% of unpaid tax.' },
    ],
    cta: 'Book a Tax Consultation',
  },
  {
    slug: 'accounting-bookkeeping',
    title: 'Accounting & Bookkeeping',
    tagline: 'Clean Books. Clear Decisions. Confident Growth.',
    description: "Your financial records are the heartbeat of your business. Star One's accounting team delivers accurate, timely, and audit-ready bookkeeping so you always know exactly where you stand.",
    icon: '📒',
    heroStat: 'Monthly',
    heroStatLabel: 'Reporting cycle',
    features: [
      { title: 'Monthly Bookkeeping', description: 'Complete recording of all financial transactions — sales, purchases, expenses, and bank reconciliations.' },
      { title: 'Financial Statements', description: 'Monthly P&L statements, balance sheets, and cash flow reports that give you a clear picture of business performance.' },
      { title: 'Payroll (WPS)', description: 'Full payroll processing compliant with UAE Wage Protection System (WPS) — salaries, deductions, and payslips.' },
      { title: 'Accounts Payable/Receivable', description: 'Systematic tracking of what you owe and what you are owed — with ageing reports and follow-up support.' },
      { title: 'Bank Reconciliation', description: 'Monthly matching of your bank statements against your accounting records to catch errors and discrepancies.' },
      { title: 'Audit Preparation', description: 'Year-end financial statement preparation and full support through external audits.' },
    ],
    benefits: [
      'Always audit-ready — no scrambling at year end',
      'Real-time visibility into your financial position',
      'Accurate data for smarter business decisions',
      'Full WPS compliance — avoid Ministry of Labour penalties',
      'Dedicated accountant who knows your business',
      'Scalable service as your business grows',
    ],
    process: [
      { step: '01', title: 'Onboarding', description: 'We review your existing records, set up your chart of accounts, and connect to your banking and invoice systems.' },
      { step: '02', title: 'Monthly Recording', description: 'We record all transactions, reconcile bank accounts, and categorise every expense accurately.' },
      { step: '03', title: 'Reporting', description: 'Monthly financial statements delivered to your inbox — P&L, balance sheet, and cash flow.' },
      { step: '04', title: 'Review & Advisory', description: 'Monthly review call to walk through your numbers, flag issues, and plan ahead.' },
    ],
    faq: [
      { q: 'Do I need an accountant if I use accounting software?', a: 'Software records transactions but does not interpret them, ensure compliance, or catch errors. A qualified accountant ensures accuracy, compliance, and adds strategic value.' },
      { q: 'What accounting software does Star One use?', a: 'We work with QuickBooks, Zoho Books, Xero, and Wave. We can work with your existing system or set up a new one.' },
      { q: 'Is bookkeeping mandatory for UAE businesses?', a: 'Yes. UAE Commercial Companies Law requires all businesses to maintain proper financial records for a minimum of 5 years.' },
      { q: 'What is WPS and who needs it?', a: 'The Wage Protection System (WPS) is a mandatory electronic salary transfer system for all UAE businesses with employees. Non-compliance can result in fines and license suspension.' },
    ],
    cta: 'Get Clean Books Starting This Month',
  },
  {
    slug: 'corporate-services',
    title: 'Corporate Services',
    tagline: 'Every Document. Every Approval. Handled.',
    description: 'Beyond licensing and visas, running a UAE business requires a network of supporting services. Star One provides comprehensive corporate support — from bank account opening to legal translation.',
    icon: '💼',
    heroStat: '48hrs',
    heroStatLabel: 'Bank intro turnaround',
    features: [
      { title: 'Bank Account Opening', description: 'We facilitate introductions and applications with UAE\'s leading banks — Emirates NBD, ADCB, Mashreq, RAK Bank, and more.' },
      { title: 'Business Plan Drafting', description: 'Professional, bank-ready and investor-ready business plans that clearly articulate your vision and financials.' },
      { title: 'Legal Translation', description: 'Certified Arabic-English translation of all legal, corporate, and personal documents by Ministry of Justice-approved translators.' },
      { title: 'Document Attestation', description: 'End-to-end document attestation including MOFA attestation, embassy legalisation, and Apostille processing.' },
      { title: 'Notary Services', description: 'Notarisation of corporate documents, powers of attorney, shareholder agreements, and personal documents.' },
      { title: 'Will & Estate Planning', description: 'DIFC Wills and non-Muslim estate planning to protect your UAE assets and ensure smooth distribution.' },
    ],
    benefits: [
      'One point of contact for all corporate needs',
      'Faster bank account opening through established relationships',
      'Professionally drafted documents that pass scrutiny',
      'Avoid expensive delays from incorrect attestation',
      'Full support for international documents',
      'Confidential handling of all sensitive documentation',
    ],
    process: [
      { step: '01', title: 'Requirement Assessment', description: 'We identify exactly what documents, approvals, and services your situation requires.' },
      { step: '02', title: 'Document Collection', description: 'We provide a precise checklist and collect/review all required originals and certified copies.' },
      { step: '03', title: 'Processing & Submission', description: 'We handle all submissions — whether to banks, notaries, translation offices, or government bodies.' },
      { step: '04', title: 'Delivery', description: 'Completed documents delivered to you — physically or digitally — with confirmation of acceptance.' },
    ],
    faq: [
      { q: 'How long does bank account opening take?', a: 'Typically 2–6 weeks depending on the bank\'s compliance requirements and the complexity of your business structure. We expedite through established bank relationships.' },
      { q: 'Which banks do you work with?', a: 'We have relationships with Emirates NBD, ADCB, Mashreq, FAB, RAK Bank, CBD, and several international banks operating in the UAE.' },
      { q: 'What is MOFA attestation?', a: 'Ministry of Foreign Affairs (MOFA) attestation authenticates the signatures on documents issued in the UAE so they are accepted internationally.' },
      { q: 'Do I need a physical office to open a bank account?', a: 'Most UAE banks require proof of a physical office address (Ejari). Some banks accept flexi-desk arrangements for certain business types.' },
    ],
    cta: 'Enquire About Corporate Services',
  },
  {
    slug: 'hr-payroll',
    title: 'HR & Payroll Services',
    tagline: 'Build Your Team. We Handle the Rest.',
    description: 'From hiring your first employee to managing a team of 50, Star One provides complete HR and payroll support — including WPS compliance, recruitment, and HR policy setup.',
    icon: '👥',
    heroStat: 'WPS',
    heroStatLabel: 'Fully compliant payroll',
    features: [
      { title: 'Payroll Management (WPS)', description: 'Full monthly payroll processing with WPS-compliant salary transfers, payslips, and deduction management.' },
      { title: 'Employee Onboarding', description: 'End-to-end onboarding support — offer letters, employment contracts, visa processing, and systems access.' },
      { title: 'HR Policy Development', description: 'Compliant HR manuals, employee handbooks, and policy frameworks aligned with UAE Labour Law.' },
      { title: 'Recruitment Support', description: 'Access to our talent network for professional and skilled roles across industries and functions.' },
      { title: 'Training & Development', description: 'Customised training programmes for compliance, soft skills, leadership, and industry-specific topics.' },
      { title: 'Employee Offboarding', description: 'Compliant employee exits including gratuity calculation, visa cancellation, and full and final settlement.' },
    ],
    benefits: [
      'Full UAE Labour Law compliance — avoid fines',
      'Accurate gratuity calculations every time',
      'WPS compliance — no Ministry penalties',
      'Professional contracts and offer letters',
      'Faster recruitment through our talent network',
      'Reduce HR overhead and focus on your core business',
    ],
    process: [
      { step: '01', title: 'HR Audit', description: 'We review your current HR practices against UAE Labour Law requirements and identify gaps.' },
      { step: '02', title: 'Setup & Systems', description: 'We establish payroll systems, WPS registration, and HR documentation frameworks.' },
      { step: '03', title: 'Monthly Payroll', description: 'We process payroll, WPS transfers, and deliver payslips to employees every month.' },
      { step: '04', title: 'Ongoing HR Support', description: 'Contract management, policy updates, employee queries, and regulatory compliance monitoring.' },
    ],
    faq: [
      { q: 'What is gratuity and how is it calculated?', a: 'UAE Labour Law entitles employees to end-of-service gratuity of 21 days pay per year for the first 5 years, and 30 days per year thereafter, up to a maximum of 2 years\' total salary.' },
      { q: 'Is WPS mandatory for all UAE companies?', a: 'Yes. All UAE companies must register with WPS and pay salaries through it. Non-compliance can result in license suspension and fines.' },
      { q: 'What are the UAE leave entitlements?', a: 'UAE Labour Law provides: 30 calendar days annual leave (after 1 year), 90 days sick leave, and various other entitlements under the new Federal Decree Law 33 of 2021.' },
      { q: 'Can we help with labour disputes?', a: 'Yes. We advise on compliance and can help mediate and document employment disputes to minimise legal exposure.' },
    ],
    cta: 'Streamline Your HR Today',
  },
  {
    slug: 'trademark-strategy',
    title: 'Trademark & Business Strategy',
    tagline: 'Protect Your Brand. Build for Scale.',
    description: 'Your brand is one of your most valuable assets. Star One helps you register and protect your trademark in the UAE and beyond — and builds the strategic frameworks to grow your business with confidence.',
    icon: '™️',
    heroStat: '45 Days',
    heroStatLabel: 'Avg. trademark registration',
    features: [
      { title: 'UAE Trademark Registration', description: 'End-to-end trademark registration with the UAE Ministry of Economy — name, logo, tagline, and brand elements.' },
      { title: 'Trademark Search & Clearance', description: 'Thorough search of existing trademarks to identify conflicts before you invest in brand assets.' },
      { title: 'International Trademark (Madrid)', description: 'Extend your trademark protection to 100+ countries through the WIPO Madrid System.' },
      { title: 'Strategy Building', description: 'Comprehensive business strategy including market analysis, competitive positioning, and growth roadmap.' },
      { title: 'Business Plan Development', description: 'Investor-ready, bank-ready business plans with financial projections, market research, and strategic narrative.' },
      { title: 'Implementation Consulting', description: 'Ongoing advisory to execute your strategy — from market entry to team building and operational scaling.' },
    ],
    benefits: [
      'Exclusive rights to your brand in the UAE',
      'Legal protection against copycats and infringement',
      'Stronger position for licensing and franchising',
      'Investor confidence backed by registered IP',
      'Strategic clarity through professional business planning',
      'Expert guidance from experienced business consultants',
    ],
    process: [
      { step: '01', title: 'Brand Audit', description: 'We review your brand elements and conduct a comprehensive trademark availability search.' },
      { step: '02', title: 'Application Preparation', description: 'We prepare the trademark application, select the correct Nice Classification, and draft all required documents.' },
      { step: '03', title: 'Filing & Publication', description: 'We file with the UAE Ministry of Economy and manage the 30-day publication and opposition period.' },
      { step: '04', title: 'Certificate Issuance', description: 'Your trademark certificate is issued — valid for 10 years and renewable indefinitely.' },
    ],
    faq: [
      { q: 'How long does UAE trademark registration take?', a: 'The process takes approximately 45–90 days from filing to certificate, provided there are no oppositions or objections.' },
      { q: 'What can be trademarked in the UAE?', a: 'Words, logos, slogans, shapes, colours, and combinations thereof can be trademarked. Descriptive terms and generic names cannot.' },
      { q: 'Is my trademark protected in all UAE free zones?', a: 'UAE trademark registration covers the entire UAE including all free zones. Separate registrations are not required per free zone.' },
      { q: 'What happens if someone copies my brand?', a: 'With a registered trademark, you can take legal action, request customs seizure of infringing goods, and claim damages. We can refer you to UAE IP litigation specialists.' },
    ],
    cta: 'Protect Your Brand Today',
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find(s => s.slug === slug)
}

export const serviceNavItems = services.map(s => ({
  href: `/services/${s.slug}`,
  label: s.title.split(' ')[0] + ' ' + (s.title.split(' ')[1] || ''),
  fullLabel: s.title,
}))
