import type { ServiceData } from '@/types'

export const services: ServiceData[] = [
  {
    slug: 'business-setup',
    title: 'Business Setup & Company Formation',
    tagline: 'Mainland, Free Zone, and Offshore — We Set You Up Right',
    description: 'Star One handles your complete UAE company formation from start to finish. Whether you\'re choosing mainland for full market access, a free zone for ownership flexibility, or an offshore structure for holding and international operations — we guide you to the right decision and manage every step.',
    icon: '🏢',
    heroStat: '3-5 Days',
    heroStatLabel: 'Average setup time',
    features: [
      { title: 'Mainland Company Setup', description: 'Full UAE market access, eligible for government contracts, 100% foreign ownership available for most activities.' },
      { title: 'Free Zone Company Setup', description: '100% foreign ownership, 0% import/export duties, flexible office options including flexi-desk.' },
      { title: 'Offshore Company Setup', description: 'Asset protection, international holding structures, and privacy — ideal for international investors.' },
      { title: 'Trade License Issuance', description: 'We handle your DED, free zone authority, or MOEC submissions and secure your trade license.' },
      { title: 'Activity Code Selection', description: 'Expert guidance on choosing the correct business activity codes to avoid future restrictions.' },
      { title: 'Government Approvals', description: 'We coordinate all authority submissions, NOCs, and approvals on your behalf.' },
    ],
    benefits: [
      '0% personal income tax in the UAE',
      '100% foreign ownership available across structures',
      'Strategic gateway — access to global markets from Dubai',
      'Fast setup — licensed in as little as 3 business days',
      'Full support from consultation to license delivery',
      'Ongoing post-setup services under one roof',
    ],
    process: [
      { step: '01', title: 'Free Consultation', description: 'We understand your goals, budget, and activity to recommend the right structure.' },
      { step: '02', title: 'Documentation', description: 'We prepare all required documents: passport copies, business plan, MoA, and application forms.' },
      { step: '03', title: 'License Submission', description: 'We submit to the relevant authority and manage all government correspondence.' },
      { step: '04', title: 'License Issuance', description: 'Your trade license is issued and we guide you through the next steps: visa, banking, and compliance.' },
    ],
    faq: [
      { q: 'What is the difference between mainland and free zone?', a: 'Mainland companies can trade freely anywhere in the UAE and with government entities. Free zone companies operate within their zone and internationally but cannot directly trade on the UAE mainland without a distributor.' },
      { q: 'Can a foreigner own 100% of a UAE company?', a: 'Yes. Following the 2021 reforms, most mainland business activities allow 100% foreign ownership. Free zones have always allowed 100% foreign ownership.' },
      { q: 'How long does company setup take?', a: 'A standard free zone setup can be completed in 3 to 5 business days. Mainland setups typically take 5 to 10 business days depending on the activity.' },
      { q: 'Are government fees included in your packages?', a: 'Government fees and third-party charges are additional to our service fees. We communicate all costs transparently before you proceed.' },
    ],
    cta: 'Start Your Business Setup Today',
  },
  {
    slug: 'golden-visa',
    title: 'Golden Visa UAE',
    tagline: 'Long-Term Residency in the UAE — Live, Work, and Thrive',
    icon: '⭐',
    heroStat: '10 Years',
    heroStatLabel: 'Golden Visa validity',
    description: 'Experience long-term residency in the UAE through the prestigious Golden Visa program. Whether you are an investor, executive professional, or outstanding student, the Golden Visa allows you to live, work, and thrive in one of the world\'s fastest-growing economies.',
    features: [
      { title: 'Long-term residency for 5 or 10 years', description: 'Flexible visa validity options to suit your plans and circumstances.' },
      { title: 'Sponsor your family members', description: 'Bring your spouse, children, and eligible dependents to live with you in the UAE.' },
      { title: 'Freedom to live, work, or study in the UAE', description: 'Full rights to reside, work across employers, and pursue education.' },
      { title: 'No need for a local sponsor', description: 'Unlike traditional sponsorship, Golden Visa holders can operate independently.' },
      { title: 'Opportunity to invest and grow your business', description: 'Build your venture with stability and long-term residency assurance.' },
      { title: 'Access to the UAE\'s world-class lifestyle and opportunities', description: 'Enjoy premium healthcare, education, and business ecosystem.' },
    ],
    benefits: [
      'Long-term residency for 5 or 10 years',
      'Sponsor your family members',
      'Freedom to live, work, or study in the UAE',
      'No need for a local sponsor',
      'Opportunity to invest and grow your business',
      'Access to the UAE\'s world-class lifestyle and opportunities',
    ],
    process: [
      { step: '01', title: 'Consultation', description: 'We assess your eligibility and recommend the most suitable Golden Visa category.' },
      { step: '02', title: 'Documentation', description: 'Our team assists in preparing and submitting all required documents.' },
      { step: '03', title: 'Approval & Visa Issuance', description: 'Once approved, your Golden Visa will be issued, granting you long-term residency in the UAE.' },
    ],
    faq: [
      { q: 'Who qualifies for the UAE Golden Visa?', a: 'Investors, entrepreneurs, senior executives, specialised professionals, outstanding students, and humanitarian pioneers may qualify depending on meeting specific criteria in each category.' },
      { q: 'How long is the Golden Visa valid?', a: 'The Golden Visa is valid for 5 or 10 years and is renewable, providing long-term stability without needing an employer or local sponsor.' },
      { q: 'Can I sponsor my family on a Golden Visa?', a: 'Yes. Golden Visa holders can sponsor their spouse, children, and in certain cases parents and domestic workers for UAE residency.' },
    ],
    cta: 'Apply for Golden Visa',
  },
  {
    slug: 'employment-visa',
    title: 'Employment Visa UAE',
    tagline: 'Live and Work Legally in the UAE',
    icon: '💼',
    heroStat: '2 Years',
    heroStatLabel: 'Standard visa validity',
    description: 'An Employment Visa allows foreign professionals to legally live and work in the UAE under the sponsorship of a registered company. This visa is issued once an individual secures a job with a UAE-based employer and is typically valid for two years, depending on the jurisdiction. It provides employees with the ability to reside in the country, access essential services, and sponsor eligible family members while building their careers in the UAE.',
    features: [
      { title: 'Entry Permit Processing', description: 'We obtain the initial entry permit allowing the employee to enter the UAE.' },
      { title: 'Medical Fitness Test', description: 'We guide employees through the mandatory medical examination required for visa stamping.' },
      { title: 'Emirates ID', description: 'We process the biometric registration and Emirates ID issuance for all sponsored employees.' },
      { title: 'Visa Stamping', description: 'We complete the residency visa stamp in the passport, confirming legal residency status.' },
      { title: 'Labour Card', description: 'We register the employee with the Ministry of Human Resources and issue the labour card.' },
      { title: 'Visa Renewals', description: 'We manage timely renewals to ensure continuous legal residency and employment status.' },
    ],
    benefits: [
      'Full employment visa processing for your team',
      'Quick processing times through established relationships',
      'Compliant handling of all documentation',
      'Support with medical and biometric processes',
      'Timely renewals to avoid visa lapses',
      'Peace of mind for employers and employees',
    ],
    process: [
      { step: '01', title: 'Eligibility Review', description: 'We verify the employee\'s qualifications and company\'s sponsorship eligibility.' },
      { step: '02', title: 'Entry Permit', description: 'We process the initial entry permit through relevant authorities.' },
      { step: '03', title: 'Medical & Emirates ID', description: 'We guide through medical fitness tests and biometric registration.' },
      { step: '04', title: 'Visa Stamping', description: 'Final visa stamp is completed in the employee\'s passport.' },
    ],
    faq: [
      { q: 'How long does an employment visa take?', a: 'Standard processing takes 2 to 4 weeks from the date of entry permit issuance, subject to medical clearance.' },
      { q: 'Can an employee change employers?', a: 'Yes. Under the new UAE labour law, employees can transfer their visa to a new employer with proper notice and procedures.' },
      { q: 'Can I sponsor family on an employment visa?', a: 'Yes. Employment visa holders can sponsor their spouse, children under 18 (or 25 if in full-time education), and domestic helpers.' },
    ],
    cta: 'Start the Employment Visa Process',
  },
  {
    slug: 'dependent-visa',
    title: 'Dependent Visa UAE',
    tagline: 'Keep Your Family Together in the UAE',
    icon: '👨‍👩‍👧',
    heroStat: 'Family',
    heroStatLabel: 'Residency for loved ones',
    description: 'A Dependent Visa allows UAE residents to sponsor their immediate family members, including their spouse, children, and in some cases parents, to live with them in the UAE. Sponsored family members can legally reside in the country for the duration of the sponsor\'s residency visa. This visa enables families to stay together while enjoying access to the UAE\'s high standard of living, education, healthcare, and lifestyle opportunities.',
    features: [
      { title: 'Spouse Sponsorship', description: 'Sponsor your husband or wife to reside legally in the UAE under your visa.' },
      { title: 'Child Sponsorship', description: 'Sponsor your children, typically up to age 18 (or 25 if in full-time education).' },
      { title: 'Parent Sponsorship', description: 'Eligible residents can sponsor parents depending on income and accommodation criteria.' },
      { title: 'Emirates ID Processing', description: 'We manage Emirates ID registration for all sponsored dependents.' },
      { title: 'Medical & Documentation', description: 'We guide through medical fitness tests and prepare all required documents.' },
      { title: 'Renewals & Amendments', description: 'We handle timely renewals and any visa amendments as circumstances change.' },
    ],
    benefits: [
      'Keep your family together in the UAE',
      'Sponsor multiple family members',
      'Access to UAE healthcare and education for dependents',
      'Legal residency for spouse and children',
      'Flexible sponsorship based on family needs',
      'Complete support for all dependents',
    ],
    process: [
      { step: '01', title: 'Eligibility Assessment', description: 'We verify your sponsorship eligibility based on salary and accommodation.' },
      { step: '02', title: 'Documentation', description: 'We prepare all required family documents and legal certificates.' },
      { step: '03', title: 'Medical & Emirates ID', description: 'We process medical tests and biometric registration for dependents.' },
      { step: '04', title: 'Visa Issuance', description: 'Dependent visas are issued for spouse and children.' },
    ],
    faq: [
      { q: 'Can I sponsor my parents in the UAE?', a: 'Yes. Eligible residents can sponsor parents depending on meeting specific income and accommodation criteria set by UAE authorities.' },
      { q: 'What age can I sponsor my children until?', a: 'Children can be sponsored until age 18, or until age 25 if they are enrolled in full-time education.' },
      { q: 'What documents do I need for spouse sponsorship?', a: 'Typically: marriage certificate, passport copies, and proof of accommodation and income. We provide a complete checklist.' },
    ],
    cta: 'Sponsor Your Family in the UAE',
  },
  {
    slug: 'visit-visa',
    title: 'Visit Visa UAE',
    tagline: 'Enter the UAE for Tourism, Business, or Family Visits',
    icon: '✈️',
    heroStat: '30-90 Days',
    heroStatLabel: 'Typical visit duration',
    description: 'A Visit Visa allows individuals to enter the UAE for short stays for purposes such as tourism, visiting family and friends, or exploring business opportunities. Depending on the type of visa issued, visitors can stay in the country for a specific period while enjoying the UAE\'s vibrant lifestyle, attractions, and business environment. Visit visas can be sponsored by relatives, companies, or authorized travel agencies.',
    features: [
      { title: 'Tourist Visit Visa', description: 'For individuals exploring the UAE for leisure, sightseeing, and tourism purposes.' },
      { title: 'Business Visit Visa', description: 'For professionals attending meetings, conferences, or exploring investment opportunities in the UAE.' },
      { title: 'Family Visit Visa', description: 'For family members visiting UAE residents for short stays and family reunions.' },
      { title: 'Single & Multiple Entry', description: 'We arrange single-entry and multi-entry visit visas based on your travel requirements.' },
      { title: 'Extension Processing', description: 'We assist with extending visit visas when additional time in the UAE is needed.' },
      { title: 'Fast Processing', description: 'We ensure quick and accurate submissions to minimise waiting time before your trip.' },
    ],
    benefits: [
      'Quick visa processing for your trip',
      'Multiple entry options for frequent visitors',
      'Easy family visit arrangements',
      'Business visit support for networking',
      'Extension options if you need longer stay',
      'Support for last-minute applications',
    ],
    process: [
      { step: '01', title: 'Visa Type Selection', description: 'We identify the right visit visa category for your purpose.' },
      { step: '02', title: 'Documentation', description: 'We collect and verify all required documents.' },
      { step: '03', title: 'Application Submission', description: 'We submit your application to the relevant authority.' },
      { step: '04', title: 'Visa Issuance', description: 'Your visit visa is processed and issued for your trip.' },
    ],
    faq: [
      { q: 'How long is a visit visa valid?', a: 'Visit visas typically range from 30 to 90 days depending on the visa type and issuing authority.' },
      { q: 'Can I extend my visit visa?', a: 'Yes. Visit visas can be extended if you need to stay longer. We can assist with the extension process.' },
      { q: 'Who can sponsor a family visit visa?', a: 'UAE residents with valid residency visas can sponsor family members for visit visas.' },
    ],
    cta: 'Apply for a Visit Visa',
  },
  {
    slug: 'corporate-tax',
    title: 'Corporate Tax UAE',
    tagline: 'Stay Compliant with UAE\'s Federal Corporate Tax',
    icon: '📊',
    heroStat: '9%',
    heroStatLabel: 'Tax rate above AED 375,000',
    description: 'Corporate Tax is a federal tax applied to the net profits of businesses operating in the UAE. It was introduced on 1 June 2023 to align the UAE with global tax standards and improve financial transparency.',
    features: [
      { title: 'Tax Registration', description: 'Complete Federal Tax Authority registration for your business.' },
      { title: 'Compliance Setup', description: 'Ensure your accounting systems meet Corporate Tax requirements.' },
      { title: 'Annual Tax Return Filing', description: 'Accurate preparation and timely filing of your annual Corporate Tax return.' },
      { title: 'Tax Planning', description: 'Strategic advice to optimize your tax position within legal boundaries.' },
      { title: 'Documentation Support', description: 'We maintain all required documentation for tax authority audits.' },
      { title: 'Regulatory Updates', description: 'Keep you informed of any changes to Corporate Tax regulations.' },
    ],
    benefits: [
      'Avoid penalties for non-compliance or late filing',
      'Understand your tax obligations clearly',
      'Optimize your tax position legally',
      'Expert interpretation of tax regulations',
      'Timely filings every year',
      'Support during tax authority inquiries',
    ],
    process: [
      { step: '01', title: 'Tax Assessment', description: 'We review your business structure and determine your tax obligations.' },
      { step: '02', title: 'FTA Registration', description: 'We register your business with the Federal Tax Authority.' },
      { step: '03', title: 'Documentation & Records', description: 'We ensure your accounting records meet tax filing requirements.' },
      { step: '04', title: 'Annual Filing', description: 'We prepare and file your annual Corporate Tax return on time.' },
    ],
    faq: [
      { q: 'When did UAE Corporate Tax come into effect?', a: 'Corporate Tax was introduced on 1 June 2023 and applies to financial years starting on or after that date.' },
      { q: 'What is the Corporate Tax rate?', a: '0% on taxable income up to AED 375,000 and 9% on income above that threshold.' },
      { q: 'When must a business register for Corporate Tax?', a: 'Within 3 months of obtaining a trade license, even if the business has not yet started generating revenue.' },
      { q: 'Do Free Zone companies pay Corporate Tax?', a: 'Qualifying Free Zone Persons may benefit from a 0% rate on qualifying income subject to meeting specific conditions under UAE law.' },
    ],
    cta: 'Register for Corporate Tax',
  },
  {
    slug: 'vat',
    title: 'VAT — Value Added Tax',
    tagline: 'UAE VAT Registration, Filing & Compliance',
    icon: '📋',
    heroStat: '5%',
    heroStatLabel: 'Standard UAE VAT rate',
    description: 'VAT is an indirect tax applied to the sale of goods and services in the UAE. It was introduced on 1 January 2018 to support government revenue and diversify the economy. VAT is ultimately borne by the end consumer, while businesses act as collectors and remitters on behalf of the government.',
    features: [
      { title: 'VAT Registration', description: 'Mandatory or voluntary VAT registration with the Federal Tax Authority.' },
      { title: 'Quarterly Filing', description: 'Accurate quarterly VAT returns filed on time with proper documentation.' },
      { title: 'Input VAT Recovery', description: 'Optimize recovery of VAT paid on eligible business expenses.' },
      { title: 'Compliance Support', description: 'Ensure full compliance with FTA requirements and deadlines.' },
      { title: 'Record Maintenance', description: 'We maintain all invoices and records required for VAT purposes.' },
      { title: 'FTA Correspondence', description: 'We handle all communication with the Federal Tax Authority.' },
    ],
    benefits: [
      'Avoid late filing penalties and interest',
      'Maximize input VAT recovery',
      'Stay compliant with all FTA regulations',
      'Clear understanding of VAT obligations',
      'Professional quarterly returns every time',
      'Reduced administrative burden',
    ],
    process: [
      { step: '01', title: 'VAT Assessment', description: 'We determine if you must or should register for VAT.' },
      { step: '02', title: 'FTA Registration', description: 'We handle your VAT registration with the Federal Tax Authority.' },
      { step: '03', title: 'Monthly Accounting', description: 'We track VAT on all sales and purchases for accurate returns.' },
      { step: '04', title: 'Quarterly Filing', description: 'We prepare and file your VAT returns within statutory deadlines.' },
    ],
    faq: [
      { q: 'What is the UAE VAT rate?', a: 'The standard VAT rate in the UAE is 5%.' },
      { q: 'Who needs to register for VAT?', a: 'Businesses with taxable supplies exceeding AED 375,000 annually must register. Voluntary registration is available for businesses above AED 187,500.' },
      { q: 'How often do I file VAT returns?', a: 'Most businesses file quarterly. Some higher-turnover businesses may be required to file monthly.' },
      { q: 'Can I recover VAT I pay on business expenses?', a: 'Yes. Businesses can recover input VAT paid on eligible business expenses by offsetting it against VAT collected on sales.' },
    ],
    cta: 'Register for VAT',
  },
  {
    slug: 'audit',
    title: 'Audit Report',
    tagline: 'Independent Financial Review for UAE Compliance',
    icon: '🔍',
    heroStat: 'Annual',
    heroStatLabel: 'Filing frequency',
    description: 'An Audit Report is an official financial statement prepared by a licensed auditor after examining a company\'s financial records. It provides an independent and accurate view of a business\'s financial position and confirms whether the accounts comply with UAE accounting standards and regulations.',
    features: [
      { title: 'Financial Statement Review', description: 'Review of income, expenses, and balance sheet accuracy.' },
      { title: 'Accounting Record Verification', description: 'Verification of transactions and accounting practices.' },
      { title: 'Compliance Assessment', description: 'Assessment of financial accuracy and regulatory compliance.' },
      { title: 'Auditor\'s Opinion', description: 'Professional opinion on whether accounts present a true and fair view.' },
      { title: 'Audit Support', description: 'Full preparation and coordination of the external audit process.' },
      { title: 'Regulatory Reporting', description: 'Submission of audit reports to relevant authorities as required.' },
    ],
    benefits: [
      'Ensure financial transparency and accuracy',
      'Maintain legal and regulatory compliance',
      'Support Corporate Tax filings and planning',
      'Build trust with banks, investors, and authorities',
      'Identify financial issues early',
      'Professional audit documentation',
    ],
    process: [
      { step: '01', title: 'Audit Planning', description: 'We coordinate with your auditor and prepare necessary documentation.' },
      { step: '02', title: 'Record Review', description: 'We ensure all accounting records are complete and accurate.' },
      { step: '03', title: 'Audit Support', description: 'We provide all required information and documentation to the auditor.' },
      { step: '04', title: 'Report Submission', description: 'We submit the audit report to relevant authorities as required.' },
    ],
    faq: [
      { q: 'When is an audit report required?', a: 'Annually for most companies, when renewing trade licenses in many Free Zones, and for Corporate Tax compliance.' },
      { q: 'Who needs an audit report?', a: 'Mainland companies, Free Zone companies (depending on authority rules), and companies filing Corporate Tax returns.' },
      { q: 'What does an audit cost?', a: 'Costs depend on the size and complexity of your business. We can provide estimates after reviewing your financial records.' },
    ],
    cta: 'Request an Audit Report',
  },
  {
    slug: 'esr',
    title: 'ESR — Economic Substance Regulations',
    tagline: 'Demonstrate Real Business Presence in the UAE',
    icon: '🏛️',
    heroStat: 'Annual',
    heroStatLabel: 'Reporting requirement',
    description: 'ESR are UAE rules that require certain companies to show they have a real and sufficient business presence in the country. In simple terms, it ensures that businesses operating in the UAE are genuinely active and not just registered on paper. Companies that fall under ESR must carry out their core activities in the UAE and maintain proper operations such as staff, office space, and management locally.',
    features: [
      { title: 'ESR Assessment', description: 'We assess whether your business activities fall within the scope of Economic Substance Regulations.' },
      { title: 'ESR Notification', description: 'We prepare and file your annual ESR notification with the relevant regulatory authority.' },
      { title: 'ESR Report Filing', description: 'We compile and submit your ESR report demonstrating adequate economic substance in the UAE.' },
      { title: 'Substance Review', description: 'We review your operations — staff, premises, expenses — to ensure compliance with substance requirements.' },
      { title: 'Ongoing Monitoring', description: 'We track regulatory changes and keep your ESR compliance up to date each year.' },
      { title: 'Penalty Avoidance', description: 'Non-compliance can attract significant fines. We ensure timely and accurate submissions.' },
    ],
    benefits: [
      'Avoid ESR non-compliance penalties',
      'Demonstrate genuine business operations',
      'Maintain business license protection',
      'Professional compliance documentation',
      'Ongoing regulatory monitoring',
      'Peace of mind on ESR obligations',
    ],
    process: [
      { step: '01', title: 'ESR Eligibility Review', description: 'We determine if your company falls under ESR scope.' },
      { step: '02', title: 'Substance Assessment', description: 'We review your business operations and UAE presence.' },
      { step: '03', title: 'Documentation Preparation', description: 'We compile all required evidence of economic substance.' },
      { step: '04', title: 'Annual Filing', description: 'We submit your ESR notification and report to authorities.' },
    ],
    faq: [
      { q: 'Who must comply with ESR?', a: 'Companies in certain sectors, Free Zone companies engaged in holding or service activities, and businesses with significant intercompany transactions.' },
      { q: 'What are ESR penalties?', a: 'Non-filing can result in penalties of AED 20,000 for first offence and AED 50,000+ for subsequent violations, potentially leading to license suspension.' },
      { q: 'What counts as economic substance?', a: 'Staff, office space, management decisions, accounting records, and core business activities must be conducted in the UAE.' },
    ],
    cta: 'Get Your ESR Assessment',
  },
  {
    slug: 'aml',
    title: 'AML — Anti-Money Laundering',
    tagline: 'Protect Your Business and Stay Legally Compliant',
    icon: '🛡️',
    heroStat: 'Mandatory',
    heroStatLabel: 'For regulated businesses',
    description: 'AML refers to laws and procedures designed to prevent the use of the financial system for illegal activities such as money laundering, fraud, or terrorist financing. In the UAE, businesses are required to implement AML compliance measures to identify clients, monitor transactions, and report any suspicious financial activity to the relevant authorities.',
    features: [
      { title: 'AML Policy Development', description: 'We create comprehensive AML compliance policies tailored to your business.' },
      { title: 'KYC Implementation', description: 'We establish Know Your Customer (KYC) verification processes.' },
      { title: 'Transaction Monitoring', description: 'We set up systems to monitor and record financial transactions.' },
      { title: 'Suspicious Activity Reporting', description: 'We establish procedures for reporting suspicious activities to authorities.' },
      { title: 'Staff Training', description: 'We provide AML training and compliance awareness to your team.' },
      { title: 'Audit & Assessment', description: 'We conduct regular AML compliance audits and updates.' },
    ],
    benefits: [
      'Ensure financial compliance and legitimacy',
      'Protect your business from legal penalties',
      'Maintain banking relationships and credibility',
      'Professional AML framework',
      'Staff awareness and training',
      'Regular compliance updates',
    ],
    process: [
      { step: '01', title: 'AML Audit', description: 'We assess your current AML practices and identify gaps.' },
      { step: '02', title: 'Policy Development', description: 'We create tailored AML policies and procedures.' },
      { step: '03', title: 'Implementation', description: 'We implement KYC, transaction monitoring, and reporting processes.' },
      { step: '04', title: 'Ongoing Monitoring', description: 'We provide ongoing compliance support and regular updates.' },
    ],
    faq: [
      { q: 'Is AML compliance mandatory for all UAE businesses?', a: 'Designated non-financial businesses and professions (DNFBPs) including real estate agents, auditors, and company service providers are subject to AML regulations.' },
      { q: 'What is KYC?', a: 'Know Your Customer (KYC) is the process of verifying client identity and understanding their business before providing services.' },
      { q: 'What happens if I don\'t comply with AML?', a: 'Non-compliance can result in significant fines, license suspension, and legal penalties.' },
    ],
    cta: 'Get AML Compliance Support',
  },
  {
    slug: 'kyc',
    title: 'KYC — Know Your Customer',
    tagline: 'Client Verification for Secure and Compliant Business',
    icon: '🪪',
    heroStat: 'Required',
    heroStatLabel: 'Before onboarding clients',
    description: 'KYC is a mandatory verification process used by businesses to confirm the identity of their clients before providing services or opening accounts. It involves collecting and verifying key documents such as identity proof, address details, and basic business or financial information to ensure the customer is genuine and compliant with regulations. KYC is widely used in banking, company formation, and financial services to prevent fraud, money laundering, and other illegal activities, while ensuring safe and transparent business transactions.',
    features: [
      { title: 'Client Identity Verification', description: 'We verify client identity through official documentation.' },
      { title: 'Address Verification', description: 'We confirm client address through utility bills or government records.' },
      { title: 'Business Information Collection', description: 'We gather relevant business and financial information.' },
      { title: 'Risk Assessment', description: 'We assess risk profile based on KYC information.' },
      { title: 'Document Maintenance', description: 'We maintain all KYC documentation for audit and compliance purposes.' },
      { title: 'Ongoing Due Diligence', description: 'We update KYC information periodically as required.' },
    ],
    benefits: [
      'Prevent fraud and illegal activity',
      'Comply with regulatory requirements',
      'Reduce business risk',
      'Professional client verification',
      'Maintain audit-ready documentation',
      'Build secure client relationships',
    ],
    process: [
      { step: '01', title: 'KYC Process Design', description: 'We design KYC procedures tailored to your business.' },
      { step: '02', title: 'Documentation Collection', description: 'We establish processes for collecting required documents.' },
      { step: '03', title: 'Verification & Approval', description: 'We verify client information and approve onboarding.' },
      { step: '04', title: 'Records Management', description: 'We maintain all KYC records securely and systematically.' },
    ],
    faq: [
      { q: 'What documents are typically required for KYC?', a: 'Passport or national ID, address proof, business registration, and sometimes financial statements depending on the client type.' },
      { q: 'How often should KYC be refreshed?', a: 'Typically every 1-2 years or when there are significant changes to client circumstances.' },
      { q: 'Who must conduct KYC?', a: 'Banks, financial institutions, real estate agents, company formation services, and other regulated businesses must implement KYC.' },
    ],
    cta: 'Set Up Your KYC Process',
  },
  {
    slug: 'ubo',
    title: 'UBO — Ultimate Beneficial Owner',
    tagline: 'Ownership Transparency and Regulatory Compliance',
    icon: '👤',
    heroStat: '25%+',
    heroStatLabel: 'Ownership threshold for UBO',
    description: 'UBO refers to the real person who ultimately owns or controls a company, even if the business is registered in another name. In the UAE, companies must identify and maintain records of their UBOs to ensure transparency and comply with anti-money laundering regulations. It generally applies to individuals holding 25% or more ownership or control in a company.',
    features: [
      { title: 'UBO Identification', description: 'We identify all ultimate beneficial owners of your company.' },
      { title: 'UBO Register Maintenance', description: 'We maintain and update your UBO register as required by law.' },
      { title: 'Regulatory Filing', description: 'We file UBO information with the relevant regulatory authority.' },
      { title: 'Change Management', description: 'We update UBO records within required timeframes when ownership changes.' },
      { title: 'Documentation', description: 'We prepare all required UBO documentation and evidence.' },
      { title: 'Compliance Monitoring', description: 'We ensure ongoing compliance with UBO requirements.' },
    ],
    benefits: [
      'Comply with UBO registration requirements',
      'Maintain transparency with authorities',
      'Avoid compliance penalties',
      'Professional UBO documentation',
      'Timely updates for ownership changes',
      'Regulatory peace of mind',
    ],
    process: [
      { step: '01', title: 'UBO Assessment', description: 'We identify all individuals with 25%+ ownership or control.' },
      { step: '02', title: 'Documentation', description: 'We prepare UBO documentation with supporting evidence.' },
      { step: '03', title: 'Register Maintenance', description: 'We establish and maintain your UBO register.' },
      { step: '04', title: 'Regulatory Filing', description: 'We file UBO information with the relevant authority.' },
    ],
    faq: [
      { q: 'Who is considered a UBO?', a: 'Any individual holding 25% or more ownership or control in a company, either directly or indirectly.' },
      { q: 'When must I file UBO information?', a: 'Within 15 days of company formation and within 15 days of any changes to UBO details.' },
      { q: 'What documents are required for UBO filing?', a: 'Ownership documents, ID copies, and documentation showing control and decision-making authority.' },
    ],
    cta: 'Get UBO Registration Help',
  },
  {
    slug: 'personal-banking',
    title: 'Personal Bank Account Opening — UAE',
    tagline: 'Manage Your Finances with a UAE Personal Account',
    icon: '🏦',
    heroStat: '48hrs',
    heroStatLabel: 'Typical introduction time',
    description: 'Opening a personal bank account in the UAE allows individuals to manage daily finances such as salary deposits, savings, payments, and transfers. To open an account, banks typically require valid ID documents, proof of residency, and income details, along with completing KYC verification. Approval depends on the bank\'s eligibility criteria and compliance checks.',
    features: [
      { title: 'Bank Introduction', description: 'We introduce you to our network of UAE banks suited to your profile and requirements.' },
      { title: 'Document Preparation', description: 'We ensure all required documents are complete and correctly formatted before submission.' },
      { title: 'KYC Support', description: 'We guide you through the bank\'s KYC and compliance verification process.' },
      { title: 'Application Management', description: 'We follow up with the bank and keep you updated throughout the process.' },
      { title: 'Account Activation Support', description: 'We assist with completing account setup and initial activation steps.' },
      { title: 'Banking Guidance', description: 'We advise on the best account type for your financial needs and residency status.' },
    ],
    benefits: [
      'Quick introduction to suitable banks',
      'Streamlined account opening process',
      'Expert guidance through KYC verification',
      'Faster approval through established relationships',
      'Access to best account options',
      'Complete support from application to activation',
    ],
    process: [
      { step: '01', title: 'Profile Review', description: 'We review your profile and match you with suitable banks.' },
      { step: '02', title: 'Document Preparation', description: 'We prepare all required documentation to bank standards.' },
      { step: '03', title: 'Application Submission', description: 'We submit your application to your chosen bank.' },
      { step: '04', title: 'Account Activation', description: 'We support account activation and initial setup.' },
    ],
    faq: [
      { q: 'What documents do I need to open a personal account?', a: 'Valid passport, proof of residency (Ejari or utility bill), salary certificate or income proof, and completed bank application.' },
      { q: 'How long does personal account opening take?', a: 'Typically 1-7 business days depending on the bank\'s processing speed and verification requirements.' },
      { q: 'Can I open an account as a visitor/tourist?', a: 'Some banks accept account openings for visitors, though requirements may be stricter. We can explore options for you.' },
    ],
    cta: 'Open a Personal Bank Account',
  },
  {
    slug: 'corporate-banking',
    title: 'Corporate Bank Account Opening — UAE',
    tagline: 'Business Banking for UAE Companies',
    icon: '🏛️',
    heroStat: '2-6 Weeks',
    heroStatLabel: 'Typical processing time',
    description: 'Corporate banking involves opening a bank account for a company to manage business transactions such as payments, receipts, payroll, and international transfers. To open a corporate account in the UAE, banks require a trade license, shareholder documents, UBO details, and business information, along with KYC verification and compliance checks. A bank account is important for all company transactions, ensuring smooth financial operations and proper business compliance.',
    features: [
      { title: 'Bank Matching', description: 'We match your company profile to the most appropriate UAE bank for your business type and activities.' },
      { title: 'Document Preparation', description: 'We compile and review all required corporate documents: trade license, MoA, shareholder details, UBO records.' },
      { title: 'KYC & Compliance', description: 'We prepare your company for the bank\'s KYC and due diligence process.' },
      { title: 'Application Submission', description: 'We submit the application and manage all bank correspondence on your behalf.' },
      { title: 'Follow-up & Updates', description: 'We track your application status and keep you informed at every stage.' },
      { title: 'Post-Account Support', description: 'We assist with internet banking setup, signatory configuration, and initial transactions.' },
    ],
    benefits: [
      'Expert bank selection for your business',
      'Streamlined application process',
      'Faster approval through established relationships',
      'Complete documentation preparation',
      'Professional handling of compliance',
      'Support from application through activation',
    ],
    process: [
      { step: '01', title: 'Bank Selection', description: 'We identify the best banks for your company\'s industry and needs.' },
      { step: '02', title: 'Documentation Compilation', description: 'We gather all required corporate documents and verify completeness.' },
      { step: '03', title: 'Application Management', description: 'We submit the application and manage all bank communications.' },
      { step: '04', title: 'Account Setup & Training', description: 'We assist with internet banking setup and transaction initiation.' },
    ],
    faq: [
      { q: 'How long does corporate bank account opening take?', a: 'Typically 2 to 6 weeks depending on the bank\'s compliance requirements and the nature of your business.' },
      { q: 'Which banks does Star One work with?', a: 'We have relationships with Emirates NBD, ADCB, Mashreq, FAB, RAK Bank, CBD, and several other UAE banks.' },
      { q: 'Can a newly formed company open a bank account?', a: 'Yes, many banks accept applications from newly formed companies. Having a clear business plan and complete documents helps accelerate the process.' },
    ],
    cta: 'Open a Corporate Bank Account',
  },
  {
    slug: 'accounting-bookkeeping',
    title: 'Accounting & Bookkeeping',
    tagline: 'Clean Books. Clear Decisions. Confident Growth.',
    description: 'Accounting and bookkeeping services help businesses maintain accurate financial records and ensure compliance with UAE regulations. These services include recording daily transactions, managing financial statements, tracking expenses, and preparing reports that provide clear insights into a company\'s financial health. Proper accounting and bookkeeping enable businesses to make informed decisions, maintain transparency, and stay compliant with tax and regulatory requirements in the UAE.',
    icon: '📒',
    heroStat: 'Monthly',
    heroStatLabel: 'Reporting cycle',
    features: [
      { title: 'Monthly Bookkeeping', description: 'Complete recording of all financial transactions — sales, purchases, expenses, and bank reconciliations.' },
      { title: 'Financial Statements', description: 'Monthly P&L statements, balance sheets, and cash flow reports that give you a clear picture of business performance.' },
      { title: 'Payroll (WPS)', description: 'Full payroll processing compliant with UAE Wage Protection System (WPS) — salaries, deductions, and payslips.' },
      { title: 'Accounts Payable/Receivable', description: 'Systematic tracking of what you owe and what you are owed — with ageing reports and follow-up support.' },
      { title: 'Bank Reconciliation', description: 'Monthly matching of your bank statements against your accounting records to catch errors and discrepancies.' },
      { title: 'Audit Preparation', description: 'Year-end financial statement preparation and full support through external audits.' },
    ],
    benefits: [
      'Always audit-ready — no scrambling at year end',
      'Real-time visibility into your financial position',
      'Accurate data for smarter business decisions',
      'Full WPS compliance — avoid Ministry of Labour penalties',
      'Dedicated accountant who knows your business',
      'Scalable service as your business grows',
    ],
    process: [
      { step: '01', title: 'Onboarding', description: 'We review your existing records, set up your chart of accounts, and connect to your banking and invoice systems.' },
      { step: '02', title: 'Monthly Recording', description: 'We record all transactions, reconcile bank accounts, and categorise every expense accurately.' },
      { step: '03', title: 'Reporting', description: 'Monthly financial statements delivered to your inbox — P&L, balance sheet, and cash flow.' },
      { step: '04', title: 'Review & Advisory', description: 'Monthly review call to walk through your numbers, flag issues, and plan ahead.' },
    ],
    faq: [
      { q: 'Do I need an accountant if I use accounting software?', a: 'Software records transactions but does not interpret them, ensure compliance, or catch errors. A qualified accountant ensures accuracy, compliance, and adds strategic value.' },
      { q: 'What accounting software does Star One use?', a: 'We work with QuickBooks, Zoho Books, Xero, and Wave. We can work with your existing system or set up a new one.' },
      { q: 'Is bookkeeping mandatory for UAE businesses?', a: 'Yes. UAE Commercial Companies Law requires all businesses to maintain proper financial records for a minimum of 5 years.' },
      { q: 'What is WPS and who needs it?', a: 'The Wage Protection System (WPS) is a mandatory electronic salary transfer system for all UAE businesses with employees. Non-compliance can result in fines and license suspension.' },
    ],
    cta: 'Get Clean Books Starting This Month',
  },
  {
    slug: 'hr-payroll',
    title: 'HR & Payroll Services',
    tagline: 'Employee onboarding, salary processing, and payroll compliance',
    description: 'We manage employee onboarding, salary processing, and payroll compliance, ensuring accurate and timely staff payments in line with UAE regulations.',
    icon: '👥',
    heroStat: 'WPS',
    heroStatLabel: 'Fully compliant payroll',
    features: [
      { title: 'Payroll Management (WPS)', description: 'Full monthly payroll processing with WPS-compliant salary transfers, payslips, and deduction management.' },
      { title: 'Employee Onboarding', description: 'End-to-end onboarding support — offer letters, employment contracts, visa processing, and systems access.' },
      { title: 'HR Policy Development', description: 'Compliant HR manuals, employee handbooks, and policy frameworks aligned with UAE Labour Law.' },
      { title: 'Recruitment Support', description: 'Access to our talent network for professional and skilled roles across industries and functions.' },
      { title: 'Training & Development', description: 'Customised training programmes for compliance, soft skills, leadership, and industry-specific topics.' },
      { title: 'Employee Offboarding', description: 'Compliant employee exits including gratuity calculation, visa cancellation, and full and final settlement.' },
    ],
    benefits: [
      'Full UAE Labour Law compliance — avoid fines',
      'Accurate gratuity calculations every time',
      'WPS compliance — no Ministry penalties',
      'Professional contracts and offer letters',
      'Faster recruitment through our talent network',
      'Reduce HR overhead and focus on your core business',
    ],
    process: [
      { step: '01', title: 'HR Audit', description: 'We review your current HR practices against UAE Labour Law requirements and identify gaps.' },
      { step: '02', title: 'Setup & Systems', description: 'We establish payroll systems, WPS registration, and HR documentation frameworks.' },
      { step: '03', title: 'Monthly Payroll', description: 'We process payroll, WPS transfers, and deliver payslips to employees every month.' },
      { step: '04', title: 'Ongoing HR Support', description: 'Contract management, policy updates, employee queries, and regulatory compliance monitoring.' },
    ],
    faq: [
      { q: 'What is gratuity and how is it calculated?', a: 'UAE Labour Law entitles employees to end-of-service gratuity of 21 days pay per year for the first 5 years, and 30 days per year thereafter, up to a maximum of 2 years total salary.' },
      { q: 'Is WPS mandatory for all UAE companies?', a: 'Yes. All UAE companies must register with WPS and pay salaries through it. Non-compliance can result in license suspension and fines.' },
      { q: 'What are the UAE leave entitlements?', a: 'UAE Labour Law provides: 30 calendar days annual leave (after 1 year), 90 days sick leave, and various other entitlements under the new Federal Decree Law 33 of 2021.' },
    ],
    cta: 'Streamline Your HR Today',
  },
  {
    slug: 'marketing-branding',
    title: 'Marketing & Branding',
    tagline: 'Strategic marketing support and brand development',
    description: 'We help businesses build a strong identity through strategic marketing support, brand development, and promotional solutions to enhance visibility and growth.',
    icon: '🎯',
    heroStat: 'Brand',
    heroStatLabel: 'Identity development',
    features: [
      { title: 'Brand Strategy', description: 'Comprehensive brand positioning, messaging, and market differentiation.' },
      { title: 'Visual Identity', description: 'Logo design, brand guidelines, and visual asset development.' },
      { title: 'Marketing Planning', description: 'Tailored marketing strategies aligned with your business goals.' },
      { title: 'Digital Marketing', description: 'Social media, content, and online marketing support.' },
      { title: 'Brand Implementation', description: 'Support implementing your brand across all touchpoints.' },
      { title: 'Marketing Consulting', description: 'Ongoing strategic guidance for marketing initiatives.' },
    ],
    benefits: [
      'Strong, professional brand identity',
      'Consistent messaging and positioning',
      'Increased brand visibility',
      'Better market differentiation',
      'Strategic marketing approach',
      'Professional brand consulting',
    ],
    process: [
      { step: '01', title: 'Brand Audit', description: 'We assess your current brand position and market perception.' },
      { step: '02', title: 'Strategy Development', description: 'We develop comprehensive brand and marketing strategy.' },
      { step: '03', title: 'Brand Implementation', description: 'We implement brand guidelines and marketing initiatives.' },
      { step: '04', title: 'Ongoing Support', description: 'Continuous brand management and marketing optimization.' },
    ],
    faq: [
      { q: 'What does brand strategy include?', a: 'Market analysis, competitor positioning, target audience definition, messaging strategy, and visual identity guidelines.' },
      { q: 'How long does brand development take?', a: 'Typically 4-8 weeks depending on the scope and complexity of your requirements.' },
    ],
    cta: 'Build Your Brand Today',
  },
  {
    slug: 'trademark-strategy',
    title: 'Trademark Registration',
    tagline: 'Protect your brand with legal trademark registration',
    description: 'We assist in protecting your brand by handling trademark registration, ensuring your business name, logo, and identity are legally secured in the UAE and internationally.',
    icon: '™️',
    heroStat: '45 Days',
    heroStatLabel: 'Avg. trademark registration',
    features: [
      { title: 'UAE Trademark Registration', description: 'End-to-end trademark registration with the UAE Ministry of Economy — name, logo, tagline, and brand elements.' },
      { title: 'Trademark Search & Clearance', description: 'Thorough search of existing trademarks to identify conflicts before you invest in brand assets.' },
      { title: 'International Trademark (Madrid)', description: 'Extend your trademark protection to 100+ countries through the WIPO Madrid System.' },
      { title: 'Trademark Monitoring', description: 'Ongoing monitoring of your trademark for potential infringements.' },
      { title: 'Renewal Management', description: 'Timely trademark renewals to maintain continuous protection.' },
      { title: 'Infringement Support', description: 'Legal support if your trademark is infringed or copied.' },
    ],
    benefits: [
      'Exclusive rights to your brand in the UAE',
      'Legal protection against copycats and infringement',
      'Stronger position for licensing and franchising',
      'Investor confidence backed by registered IP',
      'International protection options',
      'Peace of mind with legal registration',
    ],
    process: [
      { step: '01', title: 'Trademark Search', description: 'We conduct comprehensive search of existing trademarks for conflicts.' },
      { step: '02', title: 'Application Preparation', description: 'We prepare the trademark application with correct Nice Classification.' },
      { step: '03', title: 'Filing & Publication', description: 'We file with the UAE Ministry of Economy and manage publication period.' },
      { step: '04', title: 'Certificate Issuance', description: 'Your trademark certificate is issued valid for 10 years and renewable.' },
    ],
    faq: [
      { q: 'How long does UAE trademark registration take?', a: 'The process takes approximately 45–90 days from filing to certificate, provided there are no oppositions or objections.' },
      { q: 'What can be trademarked in the UAE?', a: 'Words, logos, slogans, shapes, colours, and combinations thereof can be trademarked. Descriptive terms and generic names cannot.' },
      { q: 'How long is a trademark valid?', a: 'UAE trademarks are valid for 10 years and are renewable indefinitely for additional 10-year periods.' },
    ],
    cta: 'Protect Your Brand Today',
  },
  {
    slug: 'will-services',
    title: 'Will Services UAE',
    tagline: 'Secure Your Assets and Protect Your Family\'s Future',
    icon: '📜',
    heroStat: 'DIFC Wills',
    heroStatLabel: 'Legally registered in UAE',
    description: 'We support clients in drafting and registering legally valid wills in the UAE, ensuring proper asset distribution and peace of mind for families. A registered will provides legal certainty for expatriates and residents regarding how their UAE assets and custody of children will be managed in the event of their passing.',
    features: [
      { title: 'DIFC Will Registration', description: 'Professional will drafting and registration under DIFC law — chosen by many expatriates.' },
      { title: 'Non-Muslim Estate Planning', description: 'Will services for non-Muslim individuals under UAE common law.' },
      { title: 'Asset Documentation', description: 'Proper documentation and listing of all UAE and international assets.' },
      { title: 'Guardianship Specification', description: 'Clear guardianship provisions for minor children.' },
      { title: 'Executor Appointment', description: 'Appointment of trusted executors to manage your estate.' },
      { title: 'Estate Administration Support', description: 'Support with will registration and ongoing estate planning.' },
    ],
    benefits: [
      'Legal certainty for asset distribution',
      'Peace of mind for your family',
      'Clear guardianship for minor children',
      'Proper UAE asset documentation',
      'International asset considerations',
      'Professional will administration',
    ],
    process: [
      { step: '01', title: 'Will Consultation', description: 'We discuss your wishes, assets, and family situation.' },
      { step: '02', title: 'Will Drafting', description: 'We draft a legally valid will reflecting your intentions.' },
      { step: '03', title: 'Will Registration', description: 'We register your will with the appropriate UAE authority.' },
      { step: '04', title: 'Document Safe-Keeping', description: 'We help arrange secure storage of your will and documents.' },
    ],
    faq: [
      { q: 'What is a DIFC Will?', a: 'A DIFC (Dubai International Financial Centre) Will is a legally valid will that allows expatriates to determine how their UAE assets and family matters are handled, independent of UAE inheritance law.' },
      { q: 'Who should register a will?', a: 'Any UAE resident, especially expatriates, should register a will to ensure their assets are distributed according to their wishes.' },
      { q: 'Can I change my will later?', a: 'Yes. Wills can be updated or amended at any time through amendments or new will registration.' },
    ],
    cta: 'Register Your Will in the UAE',
  },
  {
    slug: 'document-attestation',
    title: 'Document Attestation',
    tagline: 'Authenticate Your Documents for UAE and International Use',
    icon: '📋',
    heroStat: 'MOFA',
    heroStatLabel: 'Ministry authenticated',
    description: 'We provide end-to-end document attestation services for personal and corporate documents, making them legally valid for use within the UAE and internationally. Document attestation confirms the authenticity of official documents through a chain of verification by relevant authorities.',
    features: [
      { title: 'MOFA Attestation', description: 'Ministry of Foreign Affairs authentication for UAE-issued documents.' },
      { title: 'Embassy Legalisation', description: 'Authentication by the relevant embassy or consulate for international use.' },
      { title: 'Apostille', description: 'Apostille certification for countries party to the Hague Convention.' },
      { title: 'Educational Certificate Attestation', description: 'Attestation of degrees, diplomas, and transcripts.' },
      { title: 'Corporate Document Attestation', description: 'Authentication of company documents, MoAs, and board resolutions.' },
      { title: 'Translation & Attestation', description: 'Certified Arabic-English translation combined with attestation.' },
    ],
    benefits: [
      'Documents accepted internationally',
      'Proper legal authentication',
      'Professional attestation handling',
      'Fast processing times',
      'Complete documentation support',
      'Peace of mind with legal validity',
    ],
    process: [
      { step: '01', title: 'Document Review', description: 'We review your documents and determine the right attestation type.' },
      { step: '02', title: 'Attestation Processing', description: 'We submit documents for MOFA, embassy, or apostille authentication.' },
      { step: '03', title: 'Translation (if needed)', description: 'We provide certified translation if required.' },
      { step: '04', title: 'Document Delivery', description: 'Attested documents are delivered to you or your recipient.' },
    ],
    faq: [
      { q: 'What is the difference between MOFA attestation and apostille?', a: 'MOFA attestation is for UAE-issued documents used internationally. Apostille is for countries party to the Hague Convention. The choice depends on where the document will be used.' },
      { q: 'How long does document attestation take?', a: 'Typically 5-15 business days depending on the type of attestation and current authority processing times.' },
      { q: 'Can I attest documents outside the UAE?', a: 'Yes. Many documents can be attested through UAE embassies in other countries for documents issued outside the UAE.' },
    ],
    cta: 'Attest Your Documents',
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find(s => s.slug === slug)
}

export const serviceNavItems = services.map(s => ({
  href: `/services/${s.slug}`,
  label: s.title.split(' ')[0] + ' ' + (s.title.split(' ')[1] || ''),
  fullLabel: s.title,
}))
